### ISSUE TITLE
Pushing to PyPi

### ISSUE THREAD

**Issue by syed** [sigmavirus24/requests-toolbelt#101]
It is possible to push a new version of this repo on pypi? The latest requests package gives import errors and the _compat.py is not available on the version present in pypi

**Comment by sigmavirus24** [comment]
Can you provide tracebacks (or even just one) to demonstrate the problem? Your bug report is speaking of tracebacks from requests and it's not clear you're bug is with the toolbelt.

**Comment by syed** [comment]
Here is what is happening.

```
syed@syed-UX303LN: ~ $ sudo pip install requests_toolbelt
Collecting requests-toolbelt
  Using cached requests_toolbelt-0.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests<=3.0.0,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from requests-toolbelt)
Installing collected packages: requests-toolbelt

Successfully installed requests-toolbelt-0.4.0
syed@syed-UX303LN: ~ $ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests_toolbelt import SSLAdapter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/ssl.py", line 13, in <module>
    from requests.packages.urllib3.poolmanager import PoolManager
ImportError: No module named packages.urllib3.poolmanager
>>> 
syed@syed-UX303LN: ~ $ pip freeze | grep requests
requests==2.7.0
requests-oauthlib==0.4.2
requests-toolbelt==0.4.0
syed@syed-UX303LN: ~ $ python --version
Python 2.7.6
syed@syed-UX303LN: ~ $ 

```

**Comment by sigmavirus24** [comment]
How did you install requests?

**Comment by sigmavirus24** [comment]
Ah nevermind. I get it now. Sorry for not quite getting this at first. We're about [50% of the way towards a 0.5.0 release](https://github.com/sigmavirus24/requests-toolbelt/milestones/0.5) and the additions since 0.4.0 mean we cannot release 0.4.1 (semantically).

**Comment by syed** [comment]
I find it kind of strange that the import fails. Clearly `poolmanager` is present in the path given in the stracktrace. 

```
syed@syed-UX303LN: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3 $ ls poolmanager.py
poolmanager.py
```

**Comment by sigmavirus24** [comment]
Do you have another file in your current working directory called `requests.py` by any chance? if so that's the root of this problem.

**Comment by syed** [comment]
nope ... but I did find

**Comment by syed** [comment]
I'm positive that is what is happening. I'll close this. Sorry for the trouble.

**Comment by sigmavirus24** [comment]
No worries.
