### ISSUE TITLE
AttributeError when using HTTPProxyDigestAuth

### ISSUE THREAD

**Issue by pcreech** [sigmavirus24/requests-toolbelt#122]
I'm attempting to utilize HTTPProxyDigestAuth, and I get an attribute error every time.  From what I can tell, it's calling cookies.parse_dict_header at line 60

I'm testing this against a squid proxy I stood up in a VM, with the following test code.

```python
#from requests_toolbelt.auth.http_proxy_digest import HTTPProxyDigestAuth
from requests_toolbelt.auth import http_proxy_digest
import requests
import sys


proxies = { "http": "http://192.168.124.243:3128" }
auth = http_proxy_digest.HTTPProxyDigestAuth("user","user")
r = requests.get("http://www.example.com", auth=auth, proxies=proxies)
sys.stdout.write(r.text)
```

I've used this in various ways, from pip and checking out source code.  Versions 0.4.0, 0.5.1, and master.  They all end up the same.

```
Traceback (most recent call last):
  File "proxydigestauth/test.py", line 9, in <module>
    r = requests.get("http://www.example.com", auth=auth, proxies=proxies)
  File "/home/pcreech/.virtualenvs/requesttoolbelt/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pcreech/.virtualenvs/requesttoolbelt/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pcreech/.virtualenvs/requesttoolbelt/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pcreech/.virtualenvs/requesttoolbelt/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/pcreech/.virtualenvs/requesttoolbelt/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/auth/http_proxy_digest.py", line 60, in handle_407
AttributeError: 'module' object has no attribute 'parse_dict_header'
```

**Comment by Lukasa** [comment]
Good catch! That function isn't in `cookies` (and may never have been), it's in `requests.utils`.

**Comment by pcreech** [comment]
I'm really trying to get this to work, so I'll probably hack it up anyways.  Open to me making a PR for it in a couple weeks?

**Comment by Lukasa** [comment]
Absolutely, that'd be great. =)
