### ISSUE TITLE
urllib3 woes given requests 2.12.0

### ISSUE THREAD

**Issue by huntc** [sigmavirus24/requests-toolbelt#167]
The requests library version 2.12.0 of a day or so ago breaks requests-toolkit 0.7.0. We believe that the issue is in relation to requests having upgraded its bundled urllib3 from 1.16 to 1.19.

While this issue broke our application's installation by manifesting in a "Reason: ImportError No module named 'urlparse'", it has also more significantly broke the Travis CI pypi publish process. To work around the issue [we ensure that an earlier version of requests is installed for our CI](https://github.com/typesafehub/conductr-cli/blob/master/.travis.yml#L9).

Here is the sample output of one of our failed builds:

```
Fetching: dpl-1.8.24.gem (100%)
Successfully installed dpl-1.8.24
1 gem installed

Installing deploy dependencies
sudo: must be setuid root
--2016-11-16 04:54:14--  https://bootstrap.pypa.io/ez_setup.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.32.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.32.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12402 (12K) [text/x-python]
Saving to: `STDOUT'

 0% [                                       ] 0           --.-K/s   in 0s      


Cannot write to `-' (Success).
Collecting twine
  Downloading twine-1.8.1-py2.py3-none-any.whl
Collecting pkginfo>=1.0 (from twine)
  Downloading pkginfo-1.4.1-py2.py3-none-any.whl
Collecting clint (from twine)
  Downloading clint-0.5.1.tar.gz
Collecting requests-toolbelt>=0.5.1 (from twine)
  Using cached requests_toolbelt-0.7.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from twine)
Collecting requests>=2.5.0 (from twine)
  Downloading requests-2.12.0-py2.py3-none-any.whl (574kB)
    100% |████████████████████████████████| 583kB 2.6MB/s 
Collecting args (from clint->twine)
  Downloading args-0.1.0.tar.gz
Building wheels for collected packages: clint, args
  Running setup.py bdist_wheel for clint ... - done
  Stored in directory: /home/travis/.cache/pip/wheels/aa/65/4a/a0bceb0a6bee518b1dace4c803f24c4ac8febe55bdca0f14ed
  Running setup.py bdist_wheel for args ... - done
  Stored in directory: /home/travis/.cache/pip/wheels/0a/e0/66/35419f9f9ee41099a3631f0f308b9604bd1ffeabc066d69070
Successfully built clint args
Installing collected packages: pkginfo, args, clint, requests, requests-toolbelt, twine
Successfully installed args-0.1.0 clint-0.5.1 pkginfo-1.4.1 requests-2.12.0 requests-toolbelt-0.7.0 twine-1.8.1

Preparing deploy
Authenticated as typesafehub
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/typesafehub/conductr-cli/.git/logs/refs/stash: Directory nonexistent

Deploying application
running sdist
running egg_info
writing dependency_links to conductr_cli.egg-info/dependency_links.txt
writing top-level names to conductr_cli.egg-info/top_level.txt
writing conductr_cli.egg-info/PKG-INFO
writing requirements to conductr_cli.egg-info/requires.txt
writing entry points to conductr_cli.egg-info/entry_points.txt
reading manifest file 'conductr_cli.egg-info/SOURCES.txt'
writing manifest file 'conductr_cli.egg-info/SOURCES.txt'
running check
warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating conductr-cli-0.49
creating conductr-cli-0.49/conductr_cli
<snip>
hard linking dcos/util.py -> conductr-cli-0.49/dcos
Writing conductr-cli-0.49/setup.cfg
creating dist
Creating tar archive
removing 'conductr-cli-0.49' (and everything under it)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 49, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests/packages/urllib3/contrib/appengine.py", line 45, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/bin/twine", line 7, in <module>
    from twine.__main__ import main
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/__main__.py", line 20, in <module>
    from twine.cli import dispatch
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/cli.py", line 23, in <module>
    import requests_toolbelt
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 51, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: No module named 'urllib3'
running upload_docs
creating build
creating build/docs
error: no files found in upload directory 'build/docs'
```

**Comment by Lukasa** [comment]
Requests 2.12.1 has just been released which should resolve this problem.
