### ISSUE TITLE
AppEngineAdapter unpickling error

### ISSUE THREAD

**Issue by skravik** [sigmavirus24/requests-toolbelt#181]
Issue looks to be similar to previously fixed https://github.com/sigmavirus24/requests-toolbelt/issues/34

```python
import pickle
import requests
from requests_toolbelt.adapters import appengine

appengine.monkeypatch()
pickle.loads(pickle.dumps(requests.Session(), protocol=pickle.HIGHEST_PROTOCOL))
```

```
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/request_handler.py", line 226, in handle_interactive_request
    exec(compiled_code, self._command_globals)
  File "<string>", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "/[...]/lib/requests/adapters.py", line 139, in __setstate__
    block=self._pool_block)
  File "/[...]/lib/requests_toolbelt/adapters/appengine.py", line 80, in init_poolmanager
    self.poolmanager = _AppEnginePoolManager(self._validate_certificate)
AttributeError: 'AppEngineAdapter' object has no attribute '_validate_certificate'
```

**Comment by sigmavirus24** [comment]
I'd be thrilled to merge a pull request that fixes this.
