### ISSUE TITLE
MultipartEncoder fails with Python 3.2's http.client

### ISSUE THREAD

**Issue by yadayada** [sigmavirus24/requests-toolbelt#88]
I'm testing toolbelt 0.4.0 with requests 2.7.0 and Python ~~3.2.6~~ 3.2.3 on Debian wheezy. 

The standard MultipartEncoder example

```python
m = MultipartEncoder(
    fields={'field0': 'value', 'field1': 'value',
            'field2': ('filename', open('file.py', 'rb'), 'text/plain')}
    )

r = requests.post('http://httpbin.org/post', data=m,
                  headers={'Content-Type': m.content_type})
```

yields the following exception
```python
Traceback (most recent call last):
  File "/usr/lib/python3.2/http/client.py", line 780, in send
    self.sock.sendall(data)
TypeError: 'MultipartEncoder' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mp.py", line 10, in <module>
    headers={'Content-Type': m.content_type})
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.2/http/client.py", line 970, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.2/http/client.py", line 1008, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.2/http/client.py", line 966, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.2/http/client.py", line 815, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.2/http/client.py", line 787, in send
    "or an iterable, got %r" % type(data))
TypeError: data should be a bytes-like object or an iterable, got <class 'requests_toolbelt.multipart.encoder.MultipartEncoder'>
```

The same code, using HTTPS...
```python
Traceback (most recent call last):
  File "/usr/lib/python3.2/http/client.py", line 780, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.2/ssl.py", line 368, in sendall
    amount = len(data)
TypeError: object of type 'MultipartEncoder' has no len()

During handling of the above exception, another exception occurred:

[...]
```

After adding a `__len__` method to MultipartEncoder

```python
Traceback (most recent call last):
  File "/usr/lib/python3.2/http/client.py", line 780, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.2/ssl.py", line 371, in sendall
    v = self.send(data[count:])
TypeError: 'MultipartEncoder' object is not subscriptable
```

**Comment by sigmavirus24** [comment]
Interesting. Our tests work against 3.2.5 but don't work against 3.2.6. I wonder what the difference is here.

**Comment by yadayada** [comment]
After a bit more fiddling around, it turns out this also occurs on Ubuntu 12.04 LTS, again with Python 3.2.3, but works just fine with Python 2.7.3.

**Comment by sigmavirus24** [comment]
So which is it, 3.2.6 or 3.2.3? I need to know the exact version so that I can try to reproduce this.

**Comment by yadayada** [comment]
Sorry, it is 3.2.3. I had redacted every occurance of the erroneous version number to state '3.2.3' before making the last post, I thought you would notice.

**Comment by sigmavirus24** [comment]
Hm, I never updated this. This is a bug with the standard library [that was fixed in 3.3 and 3.4](https://bugs.python.org/issue16658). Python's 3.2 branch is still supported (I believe) and I'm talking to a core CPython developer to have this backported.

Cheers,

**Comment by sigmavirus24** [comment]
And in talking to some core developers, 3.2 isn't accepting patches any more apparently. This is bug in the stdlib and there's no good way to work around it here.

**Comment by yadayada** [comment]
Ok. Thanks for the update.

**Comment by yadayada** [comment]
Do you think this would warrant mentioning in the readme?

**Comment by sigmavirus24** [comment]
If you want to send a PR to that effect, I'd certainly accept it.

**Comment by yadayada** [comment]
You seem to grossly overestimate how much I care.
